### PR TITLE
Add kinetics detail view

### PR DESCRIPTION
**Pull request by kianmehrabani**
This change adds a detail view focused on a reaction's kinetics in a kinetic model. It contains tabular rate constant information appropriate to the kinetic form and a copyable chemkin entry for model development.

### CODE REVIEW

**Comment by kianmehrabani** [comment]
Lindemann Kinetics w/ Collider Efficiencies
lindemann-efficiencies
Multi Arrhenius Kinetics
multi
Pressure Dependent Kinetics
pdep
Multi Pressure Dependent Kinetics
multi-pdep

**Comment by kianmehrabani** [comment]
@rwest Not sure what the form of the coefficient matrix is in the `Chebyshev `model. Can you help with that?

**Comment by rwest** [comment]
Chebyshev coefficients are not human-interpretable or meaningful, so not worth worrying about rendering nicely.
A copy-paste thing for the chemkin file, and/or evaluate the rate at a given (T,P).

**Comment by kianmehrabani** [comment]
Currently [this line](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/fe6e69a94afcf40220e4980b0b772029f66fb571/rmgpy/chemkin.pyx#L1834) of a method in `rmgpy` fails for an example `Lindemann` kinetics form. This may be due to bad data, so I can evaluate on some valid data later.

**Pull request merged**
